# Generated by Django 4.1.6 on 2023-03-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('protocol', models.CharField(max_length=3)),
                ('port', models.IntegerField()),
                ('last_scan_date', models.DateTimeField(auto_now=True)),
                ('soft_name', models.CharField(max_length=100)),
                ('soft_version', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nist_vulns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(max_length=50)),
                ('softs', models.TextField(blank=True)),
                ('softs_versions', models.TextField(blank=True)),
                ('cvss_score', models.CharField(max_length=100)),
                ('cvss_vector', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('found_date', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hosts')),
            ],
        ),
        migrations.CreateModel(
            name='Bdu_vulns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdu_id', models.CharField(max_length=50)),
                ('cve', models.CharField(max_length=50)),
                ('softs', models.TextField(blank=True)),
                ('softs_versions', models.TextField(blank=True)),
                ('cvss_score', models.CharField(max_length=100)),
                ('cvss_vector', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('found_date', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hosts')),
            ],
        ),
    ]
