# Generated by Django 4.1.6 on 2023-03-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_emails_to_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emails_to_notification',
            new_name='Notify',
        ),
    ]
