# Generated by Django 3.2.18 on 2023-03-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='vulns_count',
            new_name='bdu_count',
        ),
        migrations.AddField(
            model_name='history',
            name='nist_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
